language: cpp
os: linux
dist: xenial

env:
  jobs:
    - compiler=g++-4.4
    - compiler=g++-4.9
    - compiler=g++-5
    - compiler=g++-6
    - compiler=g++-7
    - compiler=g++-8
    - compiler=g++-9

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -q update
  - sudo apt-get -y install "$compiler"

script:
  - >-
    cmake
    -G 'Unix Makefiles'
    -D CMAKE_BUILD_TYPE=Debug
    -D "CMAKE_INSTALL_PREFIX=$HOME/install"
    -D "CMAKE_CXX_COMPILER=$compiler"
    -D SAFEINT_TESTS=ON
    "-B$HOME/build"
    -H.
  - cmake --build "$HOME/build" --target install
  - "$HOME/install/bin/SafeInt_Test"
